eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///y199?CharacterEncoding=utf-8
BAIDUSELLPRODUCT:
  ribbon:
    Nfloadbalancerruleclassname: com.netflix.loadbalancer.RandomRule

